### ISSUE TITLE
Fix PF Met from re-miniAOD

### ISSUE THREAD

**Issue by blallen** [PandaPhysics/PandaTree#10]
PF Met taken out of the box from the re-miniAOD is broken. We can either run an official CMS producer from Zeynep or we can add Sid's private fix, but we should fix this for version 003 so we don't need to run it on top of panda anymore.

**Comment by sidnarayanan** [comment]
Private fix doesn't work perfectly since PF and SC matching doesn't seem to always work. Let's do it properly:

https://twiki.cern.ch/twiki/bin/view/CMSPublic/ReMiniAOD03Feb2017Notes#MET_Recipes

**Comment by sidnarayanan** [comment]
One thing to note here: the PF candidates from the fix have to be fed back into puppi and fatjets

**Comment by yiiyama** [comment]
If you are talking about applying the fix on PF candidates from the bad muon removal to MC, it is propagated everywhere.
https://github.com/PandaPhysics/PandaProd/blob/master/Producer/cfg/prod.py#L369-L372
These lines go into the analyzer and producer configs and replace packedPFCandidates with cleanMuonsPFCandidates.

**Comment by sidnarayanan** [comment]
No, I was referring to propagating the EG correction back to PF level. Related: right now we set electron pfPt by looking for a PF cand that is an electron, but sometimes it's a photon at pf level (and vice versa). Could we make it an OR of the PF IDs?

**Comment by yiiyama** [comment]
Yes, that came up with Brandon too. One of my PRs do that - I forgot which..

**Comment by yiiyama** [comment]
But I thought we don't apply EG correction to PF candidates? CMSSW recipe is to correct just the MET, no?

**Comment by yiiyama** [comment]
https://github.com/PandaPhysics/PandaProd/pull/6

This does not include fix on PF candidates though, if we want to do that.

**Comment by sidnarayanan** [comment]
Sorry, that was my mistake. We indeed don't want to propagate things to PF candidate level. https://github.com/PandaPhysics/PandaProd/pull/6 looks good to me

**Comment by yiiyama** [comment]
Sid is seeing discrepancies between nero and panda.
