### ISSUE TITLE
.dump() prints weird things for chars

### ISSUE THREAD

**Issue by dabercro** [PandaPhysics/PandaTree#105]
I notice `ptype` and `charge` print outs with strange symbols in the printout when calling `event.dump()`

**Comment by yiiyama** [comment]
Ah yes these are branches with type `unsigned char`, so stdlib `operator<<` thinks they are actually characters. We can manually edit the .cc files for these guys to cast the branch values to `int`, or we can have that casting automatically done by the generate script.

**Comment by dabercro** [comment]
Ah, yeah. I forgot that's what `B` means. I expected something like that. I think the generate script would be better so we don't have to worry in the future.

**Comment by dabercro** [comment]
I think I found it here: https://github.com/PandaPhysics/PandaTree/blob/b524ffb0818f3a6ca9fdb63c889c71cc17e2bc8d/lib/panda/branch.py#L247 Should I fix it or did you want to?

**Comment by yiiyama** [comment]
Please go ahead! Thanks.
