### ISSUE TITLE
DeepFlavor configuration changed

### ISSUE THREAD

**Issue by yiiyama** [PandaPhysics/PandaTree#111]
@sidn Do you know what we should do with the configuration change in DeepFlavor in 94X?

With these lines in setupBTag.py
` pfDeepCSVJetTags = btag.pfDeepCSVJetTags.clone(
        src = cms.InputTag(deepCSVInfosName)
    )`

in 80X we get

`cms.EDProducer("DeepFlavourJetTagsProducer",
    NNConfig = cms.FileInPath('RecoBTag/Combined/data/DeepFlavourNoSL.json'),
    src = cms.InputTag("pfDeepCSVTagInfosPuppi")
)`

but with 94X we get

`cms.EDProducer("DeepFlavourJetTagsProducer",
    NNConfig = cms.FileInPath('RecoBTag/Combined/data/DeepFlavourNoSL.json'),
    checkSVForDefaults = cms.bool(False),
    meanPadding = cms.bool(False),
    src = cms.InputTag("pfDeepCSVTagInfosAK8PFchsSubjets"),
    toAdd = cms.PSet(
        probcc = cms.string('probc')
    )
)`

Apparently `toAdd` sets up tags to be imported externally and not from the json (?). The EDProducer does not produce the products given in toAdd, so the jets sequence crash because we request probcc in makeJets.

**Comment by sidnarayanan** [comment]
I'm @sidnarayanan, not https://github.com/sidn :) 

And no, I don't know, but I will try to find out and report back.

**Comment by yiiyama** [comment]
oops

**Comment by DylanHsu** [comment]
https://github.com/cms-sw/cmssw/commit/7808091c804e443c82d8e2b884c4e1b0a83e1adf#diff-dd6ef9be3a0a66ec0d33382c840dcf53

**Comment by DylanHsu** [comment]
`probcc` has been retired. the new `DeepFlavourJetTagsProducer` will read `probc` which we add to the list of discriminator sources in `setupBTag.py`. I think we are fine here.

**Comment by yiiyama** [comment]
awesome
