### ISSUE TITLE
Run GenHFHadronMatcher in 010 producer

### ISSUE THREAD

**Issue by DylanHsu** [PandaPhysics/PandaTree#118]
Not sure how we want to store it yet, but we should somehow include the official CMSSW GenHFHadronMatcher subroutine described here:

https://twiki.cern.ch/twiki/bin/view/CMSPublic/GenHFHadronMatcher

The CFI we want to run is here
https://github.com/cms-sw/cmssw/blob/master/PhysicsTools/JetMCAlgos/python/GenHFHadronMatcher_cfi.py

**Comment by DylanHsu** [comment]
more info may be found at this Twiki page
https://twiki.cern.ch/twiki/bin/view/CMSPublic/GenHFHadronMatcher

**Comment by DylanHsu** [comment]
most of the C++ side is done, need to test
https://github.com/DylanHsu/PandaTree/commit/75c2f3b65604d70928ff674f5e60c04289e2e4fd
https://github.com/DylanHsu/PandaProd/commit/edd97d55f24e814a92f50b0506f41ac3f21c304f

**Comment by DylanHsu** [comment]
Thanks Yutaro for helping me finish setting this up. See relval plots here: http://t3serv001.mit.edu/~dhsu/relval/?d=180419_164939
(all gen jet collections now have HF hadron matching)

We have a few choices for what to do with the branches GenJet::numB(C):
- Grandfather in the old definition of numB and numC
- have some redundancy with numB(C) = size of matchedB(C)Hadrons
- remove the branches numB and numC

All changes from me:
https://github.com/PandaPhysics/PandaTree/compare/branch-010-devel...DylanHsu:branch-010-devel
https://github.com/PandaPhysics/PandaProd/compare/master...DylanHsu:dev-merger

**Comment by DylanHsu** [comment]
I forgot to mention, the test sample is `WJets_BGenFilter_Wpt-100To200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8`

**Comment by DylanHsu** [comment]
Does anyone have an opinion on what should happen to numB and numC?

@maierbenedikt @sidnarayanan @dabercro @yiiyama

**Comment by yiiyama** [comment]
I don't.

**Comment by dabercro** [comment]
I use numB for b-jet counting.

**Comment by dabercro** [comment]
I would say the best thing to do is leave the definition alone for now in the off chance something goes wrong with the new branch.

**Comment by DylanHsu** [comment]
Hi, we are all using numB right now but the whole point of this task is to not do that anymore. I agree we can keep the old definition since we have the size of the new ref vector.

**Comment by DylanHsu** [comment]
Reverted to old definition ( as computed in and around `PhysicsTools/JetMCAlgos/python/HadronAndPartonSelector_cfi.py`)

https://github.com/DylanHsu/PandaProd/commit/47d642b9b9e1d3ccb10b585c548203336af0596d
