### ISSUE TITLE
egamma GSFix - original matching

### ISSUE THREAD

**Issue by yiiyama** [PandaPhysics/PandaTree#18]
Seems like MET POG is using a simple dR < 0.1 matching between GSFixed and original egamma objects.
https://github.com/cms-met/cmssw/commit/ea443b63c13544f8228be7eebcf06e3ebdedee0f

We should align the implementation in ElectronsFiller and PhotonsFiller.

**Comment by sidnarayanan** [comment]
Just so I understand - the goal then is correct the MET using the CMSSW fix from MET POG, but then also keep `rawPt` and `originalPt` (or `pfPt`?) for EGM objects, so we can do the correction ourselves (on uncorrected MET)? You say "original egamma objects" but in the linked PR it looks like they're checking PF candidates, not the uncorrected reco objects.

**Comment by yiiyama** [comment]
Oh OK, maybe I misunderstood. Looking at the CMSSW module again now..

**Comment by yiiyama** [comment]
Sorry it took time. Looking at the MET POG recipe, what they are doing is to simply add the vector difference of GS-fixed and non-GS-fixed e/g transverse momenta into MET. The module in the PR has a function to check the PF candidates, but that's not used:

The config to run the correction on MINIAOD is
`   corMETFromMuonAndEG(process,
                    pfCandCollection="", #not needed                                                                                                                                                                                                                                                                                                                      
                    electronCollection="slimmedElectronsBeforeGSFix",
                    photonCollection="slimmedPhotonsBeforeGSFix",
                    corElectronCollection="slimmedElectrons",
                    corPhotonCollection="slimmedPhotons",
                    allMETEGCorrected=True,
                    muCorrection=False,
                    eGCorrection=True,
                    runOnMiniAOD=True,
                    postfix="MuEGClean"
                    )
`

which ignores the argument `eGPfCandMatching` (default = False). That flag is passed to
https://github.com/cms-met/cmssw/blob/ea443b63c13544f8228be7eebcf06e3ebdedee0f/PhysicsTools/PatUtils/python/tools/eGammaCorrection.py
which then sets the behavior of the CMSSW module. Since it's False, the module simply finds matching e/g objects between the fixed and non-fixed collections with dR < 0.01.

The goal is to correct the MET using this recipe, but still store rawPt and originalPt. We can keep the pfPt but it's probably not useful.

**Comment by yiiyama** [comment]
https://github.com/PandaPhysics/PandaProd/pull/3

**Comment by sidnarayanan** [comment]
https://github.com/PandaPhysics/PandaProd/pull/7
