### ISSUE TITLE
Signal weights missing

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/PandaTree#19]
We originally assumed that any signal weight would have a non-integer ID (integer IDs are reserved for QCD variations), but it appears this is not always the case. So the signal weights fail [1] and possibly incorrectly enter the scale/PDF uncertainty calculations. Unfortunately the full weight name is also missing in the LHE XML header. For the sample (montop scalar) in question, the weight IDs are 1...25. Is it safe to exclude this range from what's assumed to be QCD variations? @maierbenedikt 

[1] https://github.com/PandaPhysics/PandaProd/blob/master/Producer/src/WeightsFiller.cc#L272

**Comment by yiiyama** [comment]
PandaPhysics/PandaProd#11
