### ISSUE TITLE
Verbosity of BranchList

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/PandaTree#2]
Setting the event BranchList should have some verbose option, that should do either/or of:

- Print everything each pattern matches

- Warn if a pattern matches nothing

This way, if a branch name changes, it doesn't just fail silently. Ideally, it would also be impossible to access the Event member if the branch isn't activated, but I don't think that's trivial to do.

I can work on this feature. Just putting it here to remind myself

**Comment by yiiyama** [comment]
Good idea.
Indeed "turning off" branches is basically impossible, with the current model of directly accessing public member data.
