### ISSUE TITLE
Make getEntry work with TChain

### ISSUE THREAD

**Issue by yiiyama** [PandaPhysics/PandaTree#27]
Each CollectionBase currently holds a pointer to TBranch to look ahead the collection size (to prepare for potentially resize & reallocation of the collection). This causes a segfault when we pass a TChain as an input, because the TBranch pointer is only valid for the first tree of the chain. We need to think of a better way.

This update will not affect the data format, so we should be able to accommodate it within 003.

**Comment by sidnarayanan** [comment]
I think you want [`TTree::SetNotify`](https://root.cern.ch/doc/master/classTTree.html#aa73af03302421e4bf2a9a977356ba022). But a `TChain` can only notify a single `TObject`, so you probably want to create some class that contains a list of branches and then updates all of them when it gets notified.

**Comment by yiiyama** [comment]
#58.
