### ISSUE TITLE
GenParticle limit should be raised

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/PandaTree#31]
It's set to 256 now, but we save all gen particles, so this limit is too low. 

https://github.com/PandaPhysics/PandaTree/blob/master/panda.def#L453

Need to check if this messes up the hard-scattering particles that all analyses need. If not, this fix can go in for 004.

**Comment by yiiyama** [comment]
No worries, the limit is just the initial size of the Collection. Collections get resized as we fill them, so the problem here is only that there will always be a resize = reallocation of a big chunk of memory.

**Comment by sidnarayanan** [comment]
Ah phew! Thanks for verifying.
