### ISSUE TITLE
Missing electron IP

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/PandaTree#38]
IPs were removed from VID. Two proposals:

- Save dz and dxy

- Apply the eta-dependent cuts [1] as part of the electron ID bits

Any strong feelings either way @maierbenedikt and @yiiyama ?

[1] https://twiki.cern.ch/twiki/bin/viewauth/CMS/CutBasedElectronIdentificationRun2

**Comment by yiiyama** [comment]
+1 for saving dz and dxy.
