### ISSUE TITLE
Missing MET filters

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/PandaTree#39]
We somehow lost two of the filters in [1]. Snippet to include them:

```python
process.load('RecoMET.METFilters.BadPFMuonFilter_cfi')
process.BadPFMuonFilter.muons = cms.InputTag("slimmedMuons")
process.BadPFMuonFilter.PFCandidates = cms.InputTag("packedPFCandidates")
process.BadPFMuonFilter.taggingMode = cms.bool(True)

process.load('RecoMET.METFilters.BadChargedCandidateFilter_cfi')
process.BadChargedCandidateFilter.muons = cms.InputTag("slimmedMuons")
process.BadChargedCandidateFilter.PFCandidates = cms.InputTag("packedPFCandidates")
process.BadChargedCandidateFilter.taggingMode = cms.bool(True)
```

These are less important given the muon fix, but we might want to keep it anyway.

[1] https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2#Moriond_2017

**Comment by sidnarayanan** [comment]
Just occurred to me we're somehow missing the good primary vertex filter too. This one should go into `MetFilters::pass()` since it's a default one

**Comment by yiiyama** [comment]
We didn't have it since Bambu because it's equivalent to nvtx != 0, but it doesn't hurt to have a bit so let's add it too for clarity.
