### ISSUE TITLE
Important HLTBits bug

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/PandaTree#88]
I found that the prod-004 tag of PandaTree was reading triggers incorrectly in 004 files. I found a number of events in which the trigger should have fired, but was not picked up as such (weirdly enough it was firing a different trigger...might be the 32/64 bit issue?). Anyway, I reverted to a branch that I knew worked [1]. Will investigate this later (this was discovered trying to do some last-minute studies), but this needs to be understood and properly tagged.

[1] https://github.com/sidnarayanan/PandaTree/tree/testing-hlt

**Comment by yiiyama** [comment]
There was a bug in tree transition that was fixed by a later commit in branch-004. I'd say we should delete the current prod-004 tag and re-tag the HEAD of the branch. What do you think?

**Comment by sidnarayanan** [comment]
Ah yes sorry, that was on me to do, and I forgot. Will take care of it today.

**Comment by yiiyama** [comment]
I moved the prod-004 tag to the current master of branch-004.
