### ISSUE TITLE
GenJet quantities

### ISSUE THREAD

**Issue by sidnarayanan** [PandaPhysics/PandaTree#96]
There are 4 members of GenJet, all of which are wrong:
- `pdgid` is not the PDG ID, but rather the hadron flavor. This should be renamed
- `partonFlavor`, `numB`, and `numC` are not even filled

Not sure how this happened, but it needs to be fixed in a new release.

**Comment by dabercro** [comment]
`pdgid` is a convention we had, not a bug. The other three things filled just fine for me back in the day:
- http://t3serv001.mit.edu/~dabercro/relval/171121_192301/ak4GenJets/partonFlavor.pdf
- http://t3serv001.mit.edu/~dabercro/relval/171121_192301/ak4GenJets/numB.pdf
- http://t3serv001.mit.edu/~dabercro/relval/171121_192301/ak4GenJets/numC.pdf

Can you give more details? I can try to replicate the problem.

**Comment by dabercro** [comment]
Also, the filling problem should probably be in an issue in PandaProd to make tracking progress simpler. Renaming is up to you guys.

**Comment by dabercro** [comment]
Probably the best course of action is to extend the config files so that comments can be added and picked up by doxygen for this: https://codedocs.xyz/PandaPhysics/PandaTree/classpanda_1_1GenJet.html#pub-attribs to reduce confusion. What do you think @yiiyama ? That's something I'm happy to work on if no one else wants to.

**Comment by yiiyama** [comment]
That's a good idea. Can you do it if it doesn't take up too much time?

**Comment by dabercro** [comment]
Sure! Shouldn't be hard at all actually. It looks like you supported comments already: https://github.com/PandaPhysics/PandaTree/blob/master/defs/panda.def#L209 leads to https://github.com/PandaPhysics/PandaTree/blob/master/Objects/interface/Lepton.h#L74. I just need to make it change `//` to `///<`. We might need to do something a little fancier for functions if we want that.

I also made some improvements to the RelVal webpage generation to make branches with only a single value filled stand out. (Example: http://t3serv001.mit.edu/~dabercro/relval/?d=180126_063753) We might want to include something in the .def files to waive checks for certain branches, but that will require more thought. I'll include what I have along with more details in the PR too, if that's okay.

**Comment by sidnarayanan** [comment]
Well here's the problem... your changes are in `branch-80x`, but these weren't propagated to `master`, which is where we're developing 009.

**Comment by sidnarayanan** [comment]
Actually this seems like a bigger problem. There are a lot of changes in `branch-80x` that didn't get merged to master. I'll open a issue in PandaProd.
